const chapters = [
  {
    id: 0,
    // title: 'Luna',
    scenes: [
      {
        id: 0,
        image: '/images/0_portada_1.png',
        text: [
          { word: 'Get ready', translation: 'Prepárate' },
          { word: 'to embark on', translation: 'para emprender' },
          { word: 'a touching story', translation: 'una historia conmovedora' },
          { word: 'one that reflects', translation: 'una que refleja' },
          { word: 'the silent struggle', translation: 'la silenciosa lucha' },
          { word: 'of millions of dogs', translation: 'de millones de perros' },
          { word: 'around the world', translation: 'alrededor del mundo' },
          { word: '.', translation: '' },
          { word: 'Dogs with no home', translation: 'Perros sin hogar' },
          { word: '.', translation: '' },
          { word: 'No shelter', translation: 'Sin refugio' },
          { word: '.', translation: '' },
          { word: 'No food', translation: 'Sin comida' },
          { word: '.', translation: '' },
          { word: 'No love', translation: 'Sin amor' },
          { word: '.', translation: '' },
          { word: 'This is not', translation: 'Esta no es' },
          { word: 'just a story', translation: 'solo una historia' },
          { word: 'about a puppy', translation: 'sobre un cachorro' },
          { word: '.', translation: '' },
          {
            word: 'It’s a reminder that',
            translation: 'Es un recordatorio de que',
          },
          { word: 'behind', translation: 'detrás de' },
          { word: 'every stray', translation: 'cada animal callejero' },
          { word: 'there’s a life', translation: 'hay una vida' },
          { word: 'that longs for', translation: 'que anhela' },
          { word: 'kindness', translation: 'bondad' },
          { word: '.', translation: '' },
          { word: 'We hope that', translation: 'Esperamos que' },
          { word: 'as you read', translation: 'conforme (tú) leas' },
          { word: ',', translation: '' },
          { word: 'you feel', translation: '(tú) sientas' },
          { word: 'not only compassion', translation: 'no solo compasión' },
          { word: 'but also', translation: 'sino también' },
          { word: 'a call to action', translation: 'un llamado a la acción' },
          { word: '.', translation: '' },
          { word: 'Because the world', translation: 'Porque el mundo' },
          { word: 'doesn’t need', translation: 'no necesita' },
          {
            word: 'more stories of suffering',
            translation: 'más historias de sufrimiento',
          },
          { word: '.', translation: '' },
          { word: 'It needs', translation: 'Necesita' },
          { word: 'more people', translation: 'más personas' },
          { word: 'willing to be', translation: 'dispuestas a ser' },
          { word: 'part of the solution', translation: 'parte de la solución' },
          { word: '.', translation: '' },
        ],
      },
    ],
  },
  {
    id: 1,
    title: 'A Cold Night',
    titleTranslation: 'Una noche fría',
    scenes: [
      {
        id: 1,
        image: '/images/1.1.png',
        text: [
          { word: 'It is', translation: 'Es' },
          { word: 'a cold night', translation: 'una noche fría' },
          { word: '.', translation: '' },
          { word: 'The wind is strong', translation: 'El viento es fuerte' },
          { word: '.', translation: '' },
          {
            word: 'The moon is big and bright',
            translation: 'La luna es grande y brillante',
          },
          { word: 'in the dark sky', translation: 'en el cielo oscuro' },
          { word: '.', translation: '' },
          {
            word: 'Mama is a stray dog',
            translation: 'Mama es una perrita callejera',
          },
          { word: '.', translation: '' },
          {
            word: 'Her fur is messy',
            translation: 'Su pelaje está alborotado',
          },
          { word: '.', translation: '' },
          {
            word: 'Her eyes are tired',
            translation: 'Sus ojos están cansandos',
          },
          { word: '.', translation: '' },
          {
            word: 'Her belly is round',
            translation: 'Su vientre está redondo',
          },
          { word: '.', translation: '' },
          { word: 'She is going to', translation: 'Ella va a' },
          { word: 'have puppies', translation: 'tener cachorros' },
          { word: '.', translation: '' },
          { word: 'She walks slowly', translation: 'Ella camina lentamente' },
          { word: 'into a', translation: 'en un' },
          { word: 'quiet alley', translation: 'callejón tranquilo' },
          { word: '.', translation: '' },
          { word: 'The walls are high', translation: 'Las paredes son altas' },
          { word: '.', translation: '' },
          { word: 'The space is small', translation: 'El espacio es pequeño' },
          { word: '.', translation: '' },
          { word: 'It feels lonely', translation: 'Se siente solitario' },
          { word: '.', translation: '' },
        ],
      },
      {
        id: 2,
        image: '/images/1.2.png',
        text: [
          {
            word: 'Mama finds a corner',
            translation: 'Mama encuentra una esquina',
          },
          { word: '.', translation: '' },
          { word: 'There is a box', translation: 'Hay una caja' },
          { word: 'of cardboard', translation: 'de cartón' },
          { word: '.', translation: '' },
          { word: 'It is soft', translation: 'Es suave' },
          { word: 'and dry', translation: 'y seca' },
          { word: '.', translation: '' },
          { word: 'She lies down', translation: 'Ella se acuesta' },
          { word: 'inside the box', translation: 'dentro de la caja' },
          { word: '.', translation: '' },
          {
            word: 'She breathes deeply',
            translation: 'Ella respira profundamente',
          },
          { word: '.', translation: '' },
          { word: 'She is ready', translation: 'Ella está lista' },
          { word: '.', translation: '' },
          { word: 'One by one', translation: 'Uno por uno' },
          { word: ',', translation: '' },
          { word: 'the puppies are born', translation: 'los cachorros nacen' },
          { word: '.', translation: '' },
          { word: 'The first is black', translation: 'El primero es negro' },
          { word: '.', translation: '' },
          { word: 'The second is black', translation: 'El segundo es negro' },
          { word: 'also', translation: 'también' },
          { word: '.', translation: '' },
          { word: 'The third is', translation: 'El tercero es' },
          { word: 'light orange', translation: 'naranja claro' },
          { word: '.', translation: '' },
          { word: 'Mama looks at them', translation: 'Mama los mira' },
          { word: 'with love', translation: 'con amor' },
          { word: '.', translation: '' },
          { word: 'She licks them', translation: 'Ella los lame' },
          { word: 'gently', translation: 'suavemente' },
          { word: '.', translation: '' },
        ],
      },
      {
        id: 3,
        image: '/images/1.3.png',
        text: [
          { word: 'She tries', translation: 'Ella intenta' },
          { word: 'to feed them', translation: 'alimentarlos' },
          { word: ',', translation: '' },
          { word: 'but there is not', translation: 'pero no hay' },
          { word: 'enough milk', translation: 'suficiente leche' },
          { word: '.', translation: '' },
          { word: 'Her tummy growls', translation: 'Su panza ruge' },
          { word: '.', translation: '' },
          { word: 'She is hungry', translation: 'Ella está hambrienta' },
          { word: '.', translation: '' },
          {
            word: 'Her legs are weak',
            translation: 'Sus piernas están débiles',
          },
          { word: '.', translation: '' },
          { word: 'She wants', translation: 'Ella quiere' },
          { word: 'to find food', translation: 'encontrar comida' },
          { word: '.', translation: '' },
          { word: 'She walks out', translation: 'Ella camina fuera' },
          { word: 'of the alley', translation: 'del callejón' },
          { word: '.', translation: '' },
          { word: 'She checks', translation: 'Ella revisa' },
          { word: 'trash cans', translation: 'botes de basura' },
          { word: '.', translation: '' },
          { word: 'She finds a', translation: 'Ella encuentra un' },
          { word: 'small piece', translation: 'pequeño pedazo' },
          { word: 'of sandwich', translation: 'de sándwich' },
          { word: 'and eats it', translation: 'y lo come' },
          { word: 'fast', translation: 'rápido' },
          { word: '.', translation: '' },
          { word: 'She drinks from', translation: 'Ella bebe de' },
          { word: 'a puddle', translation: 'un charco' },
          { word: '.', translation: '' },
          { word: 'The water is grey', translation: 'El agua está gris' },
          { word: 'and sour', translation: 'y agria' },
          { word: ',', translation: '' },
          {
            word: 'but she is thirsty',
            translation: 'pero ella está sedienta',
          },
          { word: '.', translation: '' },
        ],
      },
      {
        id: 4,
        image: '/images/1.4.png',
        text: [
          { word: 'Then she turns back', translation: 'Después ella regresa' },
          { word: '.', translation: '' },
          { word: 'She wants', translation: 'Ella quiere' },
          { word: 'to see her babies', translation: 'ver a sus bebés' },
          { word: '.', translation: '' },
          {
            word: 'She crosses the street',
            translation: 'Ella cruza la calle',
          },
          { word: '.', translation: '' },
          { word: 'A car comes', translation: 'Un auto viene' },
          { word: 'too fast', translation: 'demasiado rápido' },
          { word: '.', translation: '' },
          { word: 'It hits her', translation: 'La golpea' },
          { word: '.', translation: '' },
          { word: 'Mama falls', translation: 'Mama cae' },
          { word: '.', translation: '' },
          { word: 'Her body hurts', translation: 'Su cuerpo duele' },
          { word: '.', translation: '' },
          { word: 'She lies still', translation: 'Ella permanece quieta' },
          { word: 'on the road', translation: 'en la carretera' },
          { word: '.', translation: '' },
        ],
      },
      {
        id: 5,
        image: '/images/1.5.png',
        text: [
          { word: 'The car stops', translation: 'El auto se detiene' },
          { word: 'for a moment', translation: 'por un momento' },
          { word: '.', translation: '' },
          { word: 'Mama opens', translation: 'Mama abre' },
          { word: 'her eyes', translation: 'sus ojos' },
          { word: '.', translation: '' },
          { word: 'She hopes', translation: 'Ella espera' },
          { word: 'someone will help', translation: 'que alguien la ayude' },
          { word: '.', translation: '' },
          { word: 'But the car', translation: 'Pero el auto' },
          { word: 'speeds away', translation: 'acelera y se va' },
          { word: '.', translation: '' },
          { word: 'Mama cannot move', translation: 'Mama no puede moverse' },
          { word: '.', translation: '' },
          { word: 'She thinks of', translation: 'Ella piensa en' },
          { word: 'her puppies', translation: 'sus cachorros' },
          { word: '.', translation: '' },
          { word: 'She lets out', translation: 'Ella deja salir' },
          { word: 'one soft howl', translation: 'un suave aullido' },
          { word: ',', translation: '' },
          {
            word: 'then closes her eyes',
            translation: 'y luego cierra sus ojos',
          },
          { word: 'forever', translation: 'para siempre' },
          { word: '.', translation: '' },
        ],
      },
    ],
  },
  {
    id: 2,
    title: 'Where is Mama?',
    titleTranslation: '¿Dónde está Mamá?',
    scenes: [
      {
        id: 1,
        image: '/images/2.1.png',
        text: [
          { word: 'Luna is in the', translation: 'Luna está en la' },
          { word: 'box', translation: 'caja' },
          { word: '.', translation: '' },
          { word: 'She is with', translation: 'Ella está con' },
          { word: 'her sisters', translation: 'sus hermanas' },
          { word: '.', translation: '' },
          { word: 'They are warm', translation: 'Ellas están calientitas' },
          { word: '.', translation: '' },
          { word: 'They are sleeping', translation: 'Ellas están durmiendo' },
          { word: '.', translation: '' },
          { word: 'Suddenly', translation: 'De repente' },
          { word: ',', translation: '' },
          { word: 'Luna hears a', translation: 'Luna oye un' },
          { word: 'long sad howl', translation: 'largo y triste aullido' },
          { word: '.', translation: '' },
          { word: 'It is Mama', translation: 'Es Mamá' },
          { word: '.', translation: '' },
          { word: 'Luna opens her eyes', translation: 'Luna abre sus ojos' },
          { word: '.', translation: '' },
          { word: 'She feels', translation: 'Ella siente' },
          { word: 'something is wrong', translation: 'que algo está mal' },
          { word: '.', translation: '' },
        ],
      },
      {
        id: 2,
        image: '/images/2.2.png',
        text: [
          { word: 'She crawls out', translation: 'Ella se arrastra fuera' },
          { word: 'of the box', translation: 'de la caja' },
          { word: '.', translation: '' },
          { word: 'Her little legs', translation: 'Sus pequeñas patas' },
          { word: 'shake', translation: 'tiemblan' },
          { word: '.', translation: '' },
          { word: 'She walks toward', translation: 'Ella camina hacia' },
          { word: 'the street', translation: 'la calle' },
          { word: '.', translation: '' },
          { word: 'She sees Mama', translation: 'Ella ve a Mamá' },
          { word: 'lying on', translation: 'tirada en' },
          { word: 'the road', translation: 'la carretera' },
          { word: '.', translation: '' },
          { word: 'Big cars pass', translation: 'Grandes autos pasan' },
          { word: 'by', translation: 'cerca' },
          { word: '.', translation: '' },
          { word: 'They honk and', translation: 'Ellos tocan la bocina y' },
          { word: 'go fast', translation: 'van rápido' },
          { word: '.', translation: '' },
          { word: 'Luna is scared', translation: 'Luna está asustada' },
          { word: '.', translation: '' },
          { word: 'She wants to help', translation: 'Ella quiere ayudar' },
          { word: '.', translation: '' },
        ],
      },
      {
        id: 3,
        image: '/images/2.3.png',
        text: [
          { word: 'People walk by', translation: 'Personas pasan cerca' },
          { word: '.', translation: '' },
          { word: 'A woman says', translation: 'Una mujer dice' },
          { word: ',', translation: '' },
          { word: '"Oh', translation: '"Oh' },
          { word: ',', translation: '' },
          { word: 'what a cute', translation: 'qué lindo' },
          { word: 'puppy!"', translation: 'cachorrito!"' },
          { word: '.', translation: '' },
          { word: 'A man smiles', translation: 'Un hombre sonríe' },
          { word: ',', translation: '' },
          { word: 'but no one', translation: 'pero nadie' },
          { word: 'stops', translation: 'se detiene' },
          { word: '.', translation: '' },
          { word: 'Someone moves Luna', translation: 'Alguien mueve a Luna' },
          { word: 'away', translation: 'lejos' },
          { word: '.', translation: '' },
          { word: 'She is pushed', translation: 'Ella es empujada' },
          { word: 'far from the', translation: 'lejos del' },
          { word: 'alley', translation: 'callejón' },
          { word: '.', translation: '' },
          { word: 'Now she is lost', translation: 'Ahora ella está perdida' },
          { word: '.', translation: '' },
          { word: 'The box is gone', translation: 'La caja está desaparecida' },
          { word: '.', translation: '' },
          {
            word: 'Her sisters are gone',
            translation: 'Sus hermanas están desaparecidas',
          },
          { word: '.', translation: '' },
        ],
      },
      {
        id: 4,
        image: '/images/2.4.png',
        text: [
          { word: 'She walks down', translation: 'Ella camina por' },
          { word: 'a big street', translation: 'una gran calle' },
          { word: '.', translation: '' },
          { word: 'Cars pass', translation: 'Autos pasan' },
          { word: '.', translation: '' },
          { word: 'People talk', translation: 'Personas hablan' },
          { word: '.', translation: '' },
          { word: 'Buildings shine', translation: 'Edificios brillan' },
          { word: '.', translation: '' },
          { word: 'Everything is loud', translation: 'Todo es ruidoso' },
          { word: '.', translation: '' },
          { word: 'Everything is new', translation: 'Todo es nuevo' },
          { word: '.', translation: '' },
          { word: 'Luna feels small', translation: 'Luna se siente pequeña' },
          { word: '.', translation: '' },
          { word: 'She is cold', translation: 'Ella está fría' },
          { word: '.', translation: '' },
          { word: 'She is hungry', translation: 'Ella está hambrienta' },
          { word: '.', translation: '' },
          { word: 'She is alone', translation: 'Ella está sola' },
          { word: '.', translation: '' },
          { word: 'She finds a', translation: 'Ella encuentra un' },
          { word: 'trash can', translation: 'basurero' },
          { word: '.', translation: '' },
          { word: 'She smells food', translation: 'Ella huele comida' },
          { word: '.', translation: '' },
          { word: 'She pulls out', translation: 'Ella saca' },
          { word: 'a piece of', translation: 'un trozo de' },
          { word: 'bread', translation: 'pan' },
          { word: '.', translation: '' },
          { word: 'She eats it', translation: 'Ella lo come' },
          { word: 'quickly', translation: 'rápidamente' },
          { word: '.', translation: '' },
          { word: 'It is dry', translation: 'Está seco' },
          { word: 'but fills her', translation: 'pero llena su' },
          { word: 'belly', translation: 'barriga' },
          { word: '.', translation: '' },
          { word: 'She sees a', translation: 'Ella ve un' },
          { word: 'puddle', translation: 'charco' },
          { word: '.', translation: '' },
          { word: 'The water is', translation: 'El agua está' },
          { word: 'dirty', translation: 'sucia' },
          { word: '.', translation: '' },
          { word: 'She drinks a', translation: 'Ella bebe un' },
          { word: 'little', translation: 'poco' },
          { word: '.', translation: '' },
        ],
      },
      {
        id: 5,
        image: '/images/2.5.png',
        text: [
          { word: 'She keeps walking', translation: 'Ella sigue caminando' },
          { word: '.', translation: '' },
          {
            word: 'Her paws are tired',
            translation: 'Sus patas están cansadas',
          },
          { word: '.', translation: '' },
          {
            word: 'People walk around her',
            translation: 'Personas caminan alrededor de ella',
          },
          { word: '.', translation: '' },
          { word: 'They do not see', translation: 'Ellos no la ven' },
          { word: 'her', translation: '' },
          { word: '.', translation: '' },
          {
            word: 'Luna finds a bench',
            translation: 'Luna encuentra una banca',
          },
          { word: '.', translation: '' },
          {
            word: 'She crawls under it',
            translation: 'Ella se arrastra debajo de ella',
          },
          { word: '.', translation: '' },
          { word: 'It is quiet there', translation: 'Está tranquilo allí' },
          { word: '.', translation: '' },
          { word: 'She curls up', translation: 'Ella se acurruca' },
          { word: 'and closes her eyes', translation: 'y cierra sus ojos' },
          { word: '.', translation: '' },
          { word: 'She misses Mama', translation: 'Ella extraña a Mamá' },
          { word: '.', translation: '' },
          {
            word: 'She misses her sisters',
            translation: 'Ella extraña a sus hermanas',
          },
          { word: '.', translation: '' },
          { word: 'But deep inside', translation: 'Pero en lo profundo' },
          { word: ',', translation: '' },
          { word: 'Luna feels strong', translation: 'Luna se siente fuerte' },
          { word: '.', translation: '' },
          {
            word: 'She whispers to herself',
            translation: 'Ella susurra para sí misma',
          },
          { word: ',', translation: '' },
          { word: '"I can do this."', translation: '"Yo puedo hacer esto."' },
          { word: 'She falls asleep', translation: 'Ella se duerme' },
          { word: 'in the big city', translation: 'en la gran ciudad' },
          { word: '.', translation: '' },
        ],
      },
    ],
  },
  {
    id: 3,
    title: 'Sofia',
    titleTranslation: 'Sofia',
    scenes: [
      {
        id: 1,
        image: '/images/3.1.png',
        text: [
          { word: 'Luna wakes up', translation: 'Luna se despierta' },
          { word: 'under the bench', translation: 'debajo del banco' },
          { word: '.', translation: '' },
          { word: 'Her nose is cold', translation: 'Su nariz está fría' },
          { word: '.', translation: '' },
          { word: 'Her belly is empty', translation: 'Su barriga está vacía' },
          { word: '.', translation: '' },
          { word: 'She walks slowly', translation: 'Ella camina lentamente' },
          { word: 'down the street', translation: 'por la calle' },
          { word: '.', translation: '' },
          { word: 'The sun is out', translation: 'El sol está afuera' },
          { word: '.', translation: '' },
          { word: 'It is Monday', translation: 'Es lunes' },
          { word: '.', translation: '' },
          {
            word: 'People are walking fast',
            translation: 'Las personas están caminando rápido',
          },
          { word: '.', translation: '' },
          { word: 'They are busy', translation: 'Ellos están ocupados' },
          { word: '.', translation: '' },
          { word: 'They do not see', translation: 'Ellos no ven' },
          { word: 'Luna', translation: 'a Luna' },
          { word: '.', translation: '' },
        ],
      },
      {
        id: 2,
        image: '/images/3.2.png',
        text: [
          { word: 'Suddenly', translation: 'De repente' },
          { word: ',', translation: '' },
          { word: 'Luna smells something', translation: 'Luna huele algo' },
          { word: 'delicious', translation: 'delicioso' },
          { word: '.', translation: '' },
          { word: 'It is tuna', translation: 'Es atún' },
          { word: '!', translation: '' },
          { word: 'She lifts her nose', translation: 'Ella levanta su nariz' },
          { word: 'and follows the smell', translation: 'y sigue el olor' },
          { word: '.', translation: '' },
          { word: 'The smell comes', translation: 'El olor viene' },
          { word: 'from a backpack', translation: 'de una mochila' },
          { word: '.', translation: '' },
          { word: 'A girl is wearing', translation: 'Una niña está usando' },
          { word: 'it', translation: 'ella' },
          { word: '.', translation: '' },
          { word: 'She has a', translation: 'Ella tiene una' },
          { word: 'soft smile', translation: 'suave sonrisa' },
          { word: '.', translation: '' },
        ],
      },
      {
        id: 3,
        image: '/images/3.3.png',
        text: [
          {
            word: 'Luna runs after her',
            translation: 'Luna corre detrás de ella',
          },
          { word: '.', translation: '' },
          { word: 'She barks', translation: 'Ella ladra' },
          { word: ',', translation: '' },
          { word: '"Woof!', translation: '"Guau!' },
          { word: 'Woof!"', translation: '¡Guau!"' },
          { word: 'But the girl', translation: 'Pero la niña' },
          {
            word: 'is listening to music',
            translation: 'está escuchando música',
          },
          { word: '.', translation: '' },
          { word: "She doesn't hear her", translation: 'Ella no la oye' },
          { word: '.', translation: '' },
          { word: 'At the stoplight', translation: 'En el semáforo' },
          { word: ',', translation: '' },
          { word: 'Luna chews the', translation: 'Luna muerde el' },
          { word: "girl's shoelace", translation: 'cordón de la niña' },
          { word: '.', translation: '' },
          { word: 'It gets stuck', translation: 'Se queda atrapado' },
          { word: 'in her baby teeth', translation: 'en sus dientes de leche' },
          { word: '.', translation: '' },
          { word: 'The girl is ready', translation: 'La niña está lista' },
          { word: 'to cross', translation: 'para cruzar' },
          { word: '.', translation: '' },
          {
            word: 'A bike is coming',
            translation: 'Una bicicleta está viniendo',
          },
          { word: 'fast', translation: 'rápido' },
          { word: '.', translation: '' },
          { word: 'She feels a tug', translation: 'Ella siente un tirón' },
          { word: '.', translation: '' },
          { word: 'She looks down', translation: 'Ella mira hacia abajo' },
          { word: '.', translation: '' },
          { word: 'She sees Luna', translation: 'Ella ve a Luna' },
          { word: ',', translation: '' },
          { word: 'small and scared', translation: 'pequeña y asustada' },
          { word: ',', translation: '' },
          { word: 'with the shoelace', translation: 'con el cordón' },
          { word: 'in her mouth', translation: 'en su boca' },
          { word: '.', translation: '' },
        ],
      },
      {
        id: 4,
        image: '/images/3.4.png',
        text: [
          { word: 'Luna is black', translation: 'Luna es negra' },
          { word: 'with a white spot', translation: 'con una mancha blanca' },
          { word: 'on her forehead', translation: 'en su frente' },
          { word: '.', translation: '' },
          { word: 'The spot looks', translation: 'La mancha parece' },
          { word: 'like a moon', translation: 'como una luna' },
          { word: '.', translation: '' },
          { word: 'The girl kneels', translation: 'La niña se arrodilla' },
          { word: 'down', translation: '' },
          { word: '.', translation: '' },
          { word: 'She laughs a little', translation: 'Ella ríe un poco' },
          { word: '.', translation: '' },
          { word: '"Oh!', translation: '"¡Oh!' },
          { word: 'You saved me!"', translation: '¡Tú me salvaste!"' },
          { word: 'I almost got hit,"', translation: 'Casi fui atropellada,"' },
          { word: 'she says', translation: 'dice ella' },
          { word: '.', translation: '' },
          { word: '"You are a', translation: '"Eres una' },
          { word: 'tiny hero."', translation: 'pequeña heroína."' },
          { word: '"My name is Sofia,"', translation: '"Mi nombre es Sofía,"' },
          { word: 'she adds', translation: 'ella añade' },
          { word: '.', translation: '' },
        ],
      },
      {
        id: 5,
        image: '/images/3.5.png',
        text: [
          { word: 'Sofia takes off', translation: 'Sofia se quita' },
          { word: 'her backpack', translation: 'su mochila' },
          { word: '.', translation: '' },
          { word: 'She gives Luna', translation: 'Ella le da a Luna' },
          { word: 'a piece of', translation: 'un pedazo de' },
          { word: 'her sandwich', translation: 'su sándwich' },
          { word: '.', translation: '' },
          { word: 'Luna eats it', translation: 'Luna lo come' },
          { word: 'fast', translation: 'rápidamente' },
          { word: '.', translation: '' },
          { word: 'She wags her tail', translation: 'Ella mueve su cola' },
          { word: '.', translation: '' },
          { word: 'Sofia smiles', translation: 'Sofia sonríe' },
          { word: '.', translation: '' },
          { word: '"You are coming', translation: '"Tú vas a venir' },
          { word: 'with me."', translation: 'conmigo."' },
          { word: 'I have to go', translation: 'Tengo que ir' },
          { word: 'to school now', translation: 'a la escuela ahora' },
          { word: ',', translation: '' },
          { word: 'but later', translation: 'pero más tarde' },
          { word: ',', translation: '' },
          { word: 'we go home', translation: 'nosotras iremos a casa' },
          { word: '.', translation: '' },
          { word: '"', translation: '' },
          { word: 'She gently places', translation: 'Ella suavemente coloca' },
          { word: 'Luna in her backpack', translation: 'a Luna en su mochila' },
          { word: '.', translation: '' },
          { word: 'Luna feels warm', translation: 'Luna se siente caliente' },
          { word: '.', translation: '' },
          { word: 'She feels safe', translation: 'Ella se siente segura' },
          { word: '.', translation: '' },
          { word: 'She sticks out', translation: 'Ella saca' },
          { word: 'her nose and', translation: 'su nariz y' },
          { word: 'looks at the world', translation: 'mira al mundo' },
          { word: '.', translation: '' },
          { word: 'For the first time', translation: 'Por primera vez' },
          { word: ',', translation: '' },
          { word: 'she is not alone', translation: 'ella no está sola' },
          { word: '.', translation: '' },
        ],
      },
    ],
  },
  {
    id: 4,
    title: 'Finding a Home',
    titleTranslation: 'En busca de un hogar',
    scenes: [
      {
        id: 1,
        image: '/images/4.1.png',
        text: [
          { word: 'Sofia and Luna arrive', translation: 'Sofia y Luna llegan' },
          { word: 'at school', translation: 'a la escuela' },
          { word: '.', translation: '' },
          { word: 'Luna stays quiet', translation: 'Luna permanece callada' },
          { word: 'inside the backpack', translation: 'dentro de la mochila' },
          { word: '.', translation: '' },
          { word: 'But in class', translation: 'Pero en clase' },
          { word: ',', translation: '' },
          { word: 'she lets out', translation: 'ella deja escapar' },
          { word: 'a tiny bark', translation: 'un pequeño ladrido' },
          { word: '.', translation: '' },
          { word: '"Arf!"', translation: '"¡Guau!"' },
          { word: 'The teacher looks', translation: 'El maestro mira' },
          { word: 'around', translation: 'alrededor' },
          { word: '.', translation: '' },
          { word: '"What was that', translation: '"¿Qué fue ese' },
          { word: 'noise?"', translation: 'ruido?"' },
          { word: 'Sofia whispers', translation: 'Sofia susurra' },
          { word: ',', translation: '' },
          { word: '"Shhh, Luna.', translation: '"Shhh, Luna.' },
          { word: 'Stay calm."', translation: 'Mantente tranquila."' },
        ],
      },
      {
        id: 2,
        image: '/images/4.2.png',
        text: [
          { word: 'After school', translation: 'Después de la escuela' },
          { word: ',', translation: '' },
          { word: 'Sofia walks home', translation: 'Sofia camina a casa' },
          { word: '.', translation: '' },
          { word: 'Her house is small', translation: 'Su casa es pequeña' },
          { word: 'and yellow', translation: 'y amarilla' },
          { word: '.', translation: '' },
          { word: 'There are flowers', translation: 'Hay flores' },
          { word: 'in the garden', translation: 'en el jardín' },
          { word: '.', translation: '' },
          { word: 'She opens the door', translation: 'Ella abre la puerta' },
          { word: '.', translation: '' },
          { word: 'Her mom is cooking', translation: 'Su mamá está cocinando' },
          { word: '.', translation: '' },
          { word: 'The smell is nice', translation: 'El olor es agradable' },
          { word: '.', translation: '' },
          { word: 'Sofia takes a', translation: 'Sofia toma una' },
          { word: 'deep breath', translation: 'profunda respiración' },
          { word: '.', translation: '' },
          { word: 'She knows her mom', translation: 'Ella sabe que su mamá' },
          {
            word: "doesn't like animals",
            translation: 'no le gustan los animales',
          },
          { word: 'in the house', translation: 'en la casa' },
          { word: '.', translation: '' },
          { word: '"Hi, Mom,"', translation: '"Hola, mamá,"' },
          { word: 'Sofia says', translation: 'Sofia dice' },
          { word: '.', translation: '' },
          { word: '"I found a dog."', translation: '"Encontré un perro."' },
          { word: 'Her name is Luna."', translation: 'Su nombre es Luna."' },
          {
            word: 'Her mom turns around',
            translation: 'Su mamá se da la vuelta',
          },
          { word: '.', translation: '' },
          { word: '"A dog?"', translation: '"¿Un perro?"' },
          {
            word: 'She says, surprised',
            translation: 'Ella dice, sorprendida',
          },
          { word: '.', translation: '' },
          {
            word: '"We don\'t have space."',
            translation: '"No tenemos espacio."',
          },
          {
            word: 'Dogs are messy."',
            translation: 'Los perros son desordenados."',
          },
          {
            word: '"She isn\'t messy."',
            translation: '"Ella no es desordenada."',
          },
          { word: 'She is sweet.', translation: 'Ella es dulce.' },
          { word: 'She saved me!"', translation: '¡Ella me salvó!"' },
          { word: 'says Sofia', translation: 'dice Sofia' },
          { word: '.', translation: '' },
          {
            word: 'Luna sits down quietly',
            translation: 'Luna se sienta tranquilamente',
          },
          { word: '.', translation: '' },
          { word: 'She wags her tail', translation: 'Ella mueve su cola' },
          { word: 'slowly', translation: 'lentamente' },
          { word: '.', translation: '' },
          { word: 'Her eyes are soft', translation: 'Sus ojos están suaves' },
          { word: '.', translation: '' },
        ],
      },
      {
        id: 3,
        image: '/images/4.3.png',
        text: [
          { word: "Sofia's mom looks", translation: 'La mamá de Sofia mira' },
          { word: 'at Luna', translation: 'a Luna' },
          { word: '.', translation: '' },
          { word: 'She thinks for', translation: 'Ella piensa por' },
          { word: 'a moment', translation: 'un momento' },
          { word: '.', translation: '' },
          { word: '"Okay," she says,', translation: '"Está bien," dice ella,' },
          {
            word: '"but she must stay',
            translation: '"pero ella debe quedarse',
          },
          { word: 'outside."', translation: 'afuera."' },
          {
            word: 'The backyard is big',
            translation: 'El patio trasero es grande',
          },
          { word: '.', translation: '' },
          { word: 'There is grass', translation: 'Hay césped' },
          { word: '.', translation: '' },
          { word: 'There is a small', translation: 'Hay una pequeña' },
          { word: 'wooden shelter', translation: 'caseta de madera' },
          { word: '.', translation: '' },
          {
            word: 'Sofia brings a blanket',
            translation: 'Sofia trae una manta',
          },
          { word: 'and a bowl', translation: 'y un tazón' },
          { word: 'of water', translation: 'de agua' },
          { word: '.', translation: '' },
          { word: 'Luna lies down', translation: 'Luna se acuesta' },
          { word: '.', translation: '' },
          { word: 'She is clean now', translation: 'Ella está limpia ahora' },
          { word: '.', translation: '' },
          { word: 'She is not cold', translation: 'Ella no está fría' },
          { word: '.', translation: '' },
          { word: 'But Luna is still', translation: 'Pero Luna aún está' },
          { word: 'learning', translation: 'aprendiendo' },
          { word: '.', translation: '' },
          { word: 'She digs in', translation: 'Ella cava en' },
          { word: 'the garden', translation: 'el jardín' },
          { word: '.', translation: '' },
          { word: 'She chews sticks', translation: 'Ella muerde palos' },
          { word: '.', translation: '' },
          { word: 'One day, she finds', translation: 'Un día, ella encuentra' },
          {
            word: "Sofia's mom's favorite",
            translation: 'los favoritos de la mamá de Sofia',
          },
          { word: 'shoes', translation: 'zapatos' },
          { word: '.', translation: '' },
          {
            word: 'She chews them too',
            translation: 'Ella los muerde también',
          },
          { word: '.', translation: '' },
          {
            word: 'The shoes are ruined',
            translation: 'Los zapatos están arruinados',
          },
          { word: '.', translation: '' },
        ],
      },
      {
        id: 4,
        image: '/images/4.4.png',
        text: [
          {
            word: "Sofia's parents are",
            translation: 'Los papás de Sofia están',
          },
          { word: 'upset', translation: 'molestos' },
          { word: '.', translation: '' },
          { word: '"This dog is', translation: '"¡Este perro es' },
          { word: 'trouble!"', translation: 'problemático!"' },
          { word: 'they shout', translation: 'ellos gritan' },
          { word: '.', translation: '' },
          { word: 'Luna hides in', translation: 'Luna se esconde en' },
          { word: 'her little house', translation: 'su pequeña casita' },
          { word: '.', translation: '' },
          { word: 'Sofia hugs her', translation: 'Sofia la abraza' },
          { word: '.', translation: '' },
          {
            word: '"Don\'t worry, Luna,"',
            translation: '"No te preocupes, Luna,"',
          },
          { word: 'she says', translation: 'ella dice' },
          { word: '.', translation: '' },
          {
            word: '"You\'re still learning."',
            translation: '"Tú aún estás aprendiendo."',
          },
          { word: 'Luna looks at', translation: 'Luna mira a' },
          { word: 'Sofia', translation: 'Sofia' },
          { word: '.', translation: '' },
          { word: 'Her eyes are big', translation: 'Sus ojos están grandes' },
          { word: '.', translation: '' },
          { word: 'Her tail moves', translation: 'Su cola se mueve' },
          { word: 'just a little', translation: 'solo un poco' },
          { word: '.', translation: '' },
          { word: 'She knows Sofia', translation: 'Ella sabe que Sofia' },
          { word: 'loves her', translation: 'la quiere' },
          { word: '.', translation: '' },
          { word: 'That gives her courage', translation: 'Eso le da valor' },
          { word: '.', translation: '' },
        ],
      },
    ],
  },
  {
    id: 5,
    title: 'Learning together',
    titleTranslation: 'Aprendiendo juntos',
    scenes: [
      {
        id: 1,
        image: '/images/5.1.png',
        text: [
          {
            word: 'Every day, Sofia plays',
            translation: 'Cada día, Sofia juega',
          },
          { word: 'with Luna', translation: 'con Luna' },
          { word: '.', translation: '' },
          { word: 'She trains her', translation: 'Ella la entrena' },
          { word: 'with care', translation: 'con cuidado' },
          { word: '.', translation: '' },
          { word: '"Sit," Sofia says', translation: '"Siéntate," dice Sofia' },
          { word: '.', translation: '' },
          { word: 'Luna sits', translation: 'Luna se sienta' },
          { word: '.', translation: '' },
          { word: '"Stay," Sofia says', translation: '"Quieto," dice Sofia' },
          { word: '.', translation: '' },
          { word: 'Luna waits', translation: 'Luna espera' },
          { word: '.', translation: '' },
          { word: '"Good girl!"', translation: '"Buena chica!"' },
          { word: 'Sofia claps and', translation: 'Sofia aplaude y' },
          { word: 'smiles', translation: 'sonríe' },
          { word: '.', translation: '' },
          { word: 'Luna is happy', translation: 'Luna está feliz' },
          { word: '.', translation: '' },
          { word: 'She wants to learn', translation: 'Ella quiere aprender' },
          { word: '.', translation: '' },
          { word: 'She wants to be', translation: 'Ella quiere ser' },
          { word: 'good', translation: 'buena' },
          { word: '.', translation: '' },
          { word: 'Sometimes she forgets', translation: 'A veces ella olvida' },
          { word: '.', translation: '' },
          { word: 'She digs a little', translation: 'Ella cava un poco' },
          { word: '.', translation: '' },
          { word: 'She chews a toy', translation: 'Ella muerde un juguete' },
          { word: '.', translation: '' },
          {
            word: 'But Sofia never shouts',
            translation: 'Pero Sofia nunca grita',
          },
          { word: '.', translation: '' },
          {
            word: 'She says, "It\'s okay."',
            translation: 'Ella dice, "Está bien."',
          },
          { word: '"You are still', translation: '"Tú todavía eres' },
          { word: 'a baby."', translation: 'una bebé."' },
          {
            word: "Sofia's parents watch",
            translation: 'Los padres de Sofia observan',
          },
          { word: '.', translation: '' },
          {
            word: 'At first, they are',
            translation: 'Al principio, ellos están',
          },
          { word: 'quiet', translation: 'callados' },
          { word: '.', translation: '' },
          {
            word: 'One morning, Luna brings',
            translation: 'Una mañana, Luna trae',
          },
          { word: "Sofia's dad the", translation: 'el papá de Sofia el' },
          { word: 'newspaper', translation: 'periódico' },
          { word: '.', translation: '' },
          { word: 'He laughs', translation: 'Él ríe' },
          { word: '.', translation: '' },
          { word: '"She is smart,"', translation: '"Ella es inteligente,"' },
          { word: 'he says', translation: 'él dice' },
          { word: '.', translation: '' },
        ],
      },
      {
        id: 2,
        image: '/images/5.2.jpeg',
        text: [
          { word: 'Later, Luna sees', translation: 'Más tarde, Luna ve' },
          { word: 'a bird in', translation: 'un pájaro en' },
          { word: 'the garden', translation: 'el jardín' },
          { word: '.', translation: '' },
          { word: 'She wants to run', translation: 'Ella quiere correr' },
          { word: 'after it', translation: 'tras él' },
          { word: '.', translation: '' },
          { word: 'But Sofia says,', translation: 'Pero Sofia dice,' },
          { word: '"Stay!"', translation: '"¡Quieto!"' },
          { word: 'and Luna stops', translation: 'y Luna se detiene' },
          { word: '.', translation: '' },
          {
            word: "Sofia's mom watches",
            translation: 'La mamá de Sofia observa',
          },
          { word: '.', translation: '' },
          { word: '"She listens now,"', translation: '"Ella obedece ahora,"' },
          { word: 'she says,', translation: 'ella dice,' },
          { word: 'surprised', translation: 'sorprendida' },
          { word: '.', translation: '' },
          { word: 'Luna feels proud', translation: 'Luna se siente orgullosa' },
          { word: '.', translation: '' },
          { word: 'Her tail moves', translation: 'Su cola se mueve' },
          { word: 'like a little', translation: 'como una pequeña' },
          { word: 'flag', translation: 'bandera' },
          { word: '.', translation: '' },
          { word: "She doesn't chew", translation: 'Ella no muerde' },
          { word: 'shoes anymore', translation: 'zapatos más' },
          { word: '.', translation: '' },
          { word: "She doesn't dig", translation: 'Ella no cava' },
          { word: 'holes', translation: 'hoyos' },
          { word: '.', translation: '' },
          { word: 'She likes to follow', translation: 'Le gusta seguir' },
          { word: 'Sofia', translation: 'a Sofia' },
          { word: '.', translation: '' },
          { word: 'She learns fast', translation: 'Ella aprende rápido' },
          { word: '.', translation: '' },
          {
            word: 'At night, Sofia sits',
            translation: 'Por la noche, Sofia se sienta',
          },
          { word: 'beside Luna in', translation: 'junto a Luna en' },
          { word: 'the backyard', translation: 'el patio trasero' },
          { word: '.', translation: '' },
          { word: 'The stars shine', translation: 'Las estrellas brillan' },
          { word: 'above', translation: 'arriba' },
          { word: '.', translation: '' },
          { word: '"You are my', translation: '"Tú eres mi' },
          { word: 'best friend,"', translation: 'mejor amiga,"' },
          { word: 'Sofia says', translation: 'dice Sofia' },
          { word: '.', translation: '' },
          { word: 'Luna licks her', translation: 'Luna lame su' },
          { word: 'hand', translation: 'mano' },
          { word: '.', translation: '' },
          { word: 'She is not just', translation: 'Ella ya no es solo' },
          { word: 'a street dog', translation: 'una perra callejera' },
          { word: 'anymore', translation: 'más' },
          { word: '.', translation: '' },
          { word: 'She is part', translation: 'Ella es parte' },
          { word: 'of the family', translation: 'de la familia' },
          { word: '.', translation: '' },
        ],
      },
    ],
  },
  {
    id: 6,
    title: 'A Visit to the Vet',
    titleTranslation: 'Una visita al veterinario',
    scenes: [
      {
        id: 1,
        image: '/images/6.1.png',
        text: [
          { word: 'It is Saturday', translation: 'Es sábado' },
          { word: 'morning', translation: 'por la mañana' },
          { word: '.', translation: '' },
          { word: 'The sky is', translation: 'El cielo está' },
          { word: 'blue', translation: 'azul' },
          { word: '.', translation: '' },
          { word: 'Sofia is happy', translation: 'Sofia está feliz' },
          { word: '.', translation: '' },
          { word: 'Today, Luna goes', translation: 'Hoy, Luna va' },
          { word: 'to the vet', translation: 'al veterinario' },
          { word: '.', translation: '' },
          { word: "She brushes Luna's", translation: 'Ella cepilla el' },
          { word: 'fur', translation: 'pelaje' },
          { word: '.', translation: '' },
          { word: '"You look beautiful,"', translation: '"Te ves hermosa,"' },
          { word: 'she says', translation: 'ella dice' },
          { word: '.', translation: '' },
          { word: 'Luna wags her', translation: 'Luna mueve su' },
          { word: 'tail', translation: 'cola' },
          { word: '.', translation: '' },
          { word: 'She thinks they', translation: 'Ella piensa que van' },
          { word: 'are going to', translation: 'al' },
          { word: 'the park', translation: 'parque' },
          { word: '.', translation: '' },
          { word: 'But they walk', translation: 'Pero ellos pasan' },
          { word: 'past the park', translation: 'por el parque' },
          { word: '.', translation: '' },
          { word: 'Luna looks around', translation: 'Luna mira alrededor' },
          { word: ',', translation: ',' },
          { word: 'confused', translation: 'confundida' },
          { word: '.', translation: '' },
        ],
      },
      {
        id: 2,
        image: '/images/6.2.png',
        text: [
          { word: 'They stop at', translation: 'Ellas se detienen en' },
          { word: 'a small clinic', translation: 'una pequeña clínica' },
          { word: '.', translation: '' },
          { word: 'There is a', translation: 'Hay un' },
          { word: 'big sign', translation: 'gran letrero' },
          { word: ':', translation: ':' },
          { word: '"Pet\'s Doctor."', translation: '"Doctor de Mascotas."' },
          { word: '"It\'s okay,', translation: '"Está bien,' },
          { word: 'Luna," Sofia says', translation: 'Luna," dice Sofia' },
          { word: '.', translation: '' },
          { word: '"The doctor will', translation: '"El doctor te' },
          { word: 'help you,"', translation: 'ayudará,"' },
          { word: 'she adds', translation: 'ella añade' },
          { word: '.', translation: '' },
          {
            word: 'Inside, Luna hides',
            translation: 'Dentro, Luna se esconde',
          },
          {
            word: "behind Sofia's legs",
            translation: 'detrás de las piernas de Sofia',
          },
          { word: '.', translation: '' },
          { word: 'The vet smiles', translation: 'El veterinario sonríe' },
          { word: '.', translation: '' },
          { word: '"Hello, little one,"', translation: '"Hola, pequeña,"' },
          { word: 'he says', translation: 'él dice' },
          { word: '.', translation: '' },
          { word: "He checks Luna's", translation: 'Él revisa los' },
          { word: 'eyes, ears, and', translation: 'ojos, oídos y' },
          { word: 'heart', translation: 'corazón' },
          { word: '.', translation: '' },
        ],
      },
      {
        id: 3,
        image: '/images/6.3.png',
        text: [
          { word: '"She is healthy,"', translation: '"Ella está sana,"' },
          { word: 'he says', translation: 'él dice' },
          { word: '.', translation: '' },
          { word: '"But she needs', translation: '"Pero ella necesita' },
          { word: 'a vaccine,"', translation: 'una vacuna,"' },
          { word: 'he adds', translation: 'él añade' },
          { word: '.', translation: '' },
          { word: 'Sofia holds Luna', translation: 'Sofia abraza a Luna' },
          { word: 'close', translation: 'cerca' },
          { word: '.', translation: '' },
          { word: '"Be brave,"', translation: '"Sé valiente,"' },
          { word: 'she whispers', translation: 'ella susurra' },
          { word: '.', translation: '' },
          { word: 'The vet gives', translation: 'El veterinario le da' },
          { word: 'Luna the shot', translation: 'a Luna la inyección' },
          { word: '.', translation: '' },
          { word: 'It is quick', translation: 'Es rápida' },
          { word: '.', translation: '' },
          { word: 'Luna makes a', translation: 'Luna hace un' },
          { word: 'tiny cry', translation: 'pequeño quejido' },
          { word: '.', translation: '' },
          { word: 'Then the vet', translation: 'Luego el veterinario' },
          { word: 'gives her a', translation: 'le da a ella una' },
          { word: 'treat', translation: 'golosina' },
          { word: '.', translation: '' },
          { word: '"She is strong,"', translation: '"Ella es fuerte,"' },
          { word: 'he says', translation: 'él dice' },
          { word: 'with a smile', translation: 'con una sonrisa' },
          { word: '.', translation: '' },
          { word: 'He gives Sofia', translation: 'Él le da a Sofia' },
          { word: 'a small pill', translation: 'una pequeña pastilla' },
          { word: '.', translation: '' },
          { word: '"For worms,"', translation: '"Para lombrices,"' },
          { word: 'he says', translation: 'él dice' },
          { word: '.', translation: '' },
          { word: '"Give it with', translation: '"Dásela con' },
          { word: 'food," he adds', translation: 'comida," añade él' },
          { word: '.', translation: '' },
          { word: 'Sofia puts it', translation: 'Sofia la guarda' },
          { word: 'in her bag', translation: 'en su bolsa' },
          { word: '.', translation: '' },
          { word: '"Thank you,', translation: '"Gracias,' },
          { word: 'Doctor," she says', translation: 'Doctor," dice ella' },
          { word: '.', translation: '' },
        ],
      },
      {
        id: 4,
        image: '/images/6.4.png',
        text: [
          { word: '"You are a', translation: '"Eres una' },
          { word: 'good friend to', translation: 'buena amiga para' },
          { word: 'her," says the', translation: 'ella," dice el' },
          { word: 'vet', translation: 'veterinario' },
          { word: '.', translation: '' },
          { word: 'They leave the', translation: 'Ellas salen de la' },
          { word: 'clinic', translation: 'clínica' },
          { word: '.', translation: '' },
          {
            word: 'Luna walks proudly',
            translation: 'Luna camina con orgullo',
          },
          { word: '.', translation: '' },
          { word: 'Sofia looks at', translation: 'Sofia la mira' },
          { word: 'her and says', translation: 'y dice' },
          { word: ',', translation: ',' },
          { word: '"You were so', translation: '"Fuiste muy' },
          { word: 'brave!"', translation: 'valiente!"' },
          { word: 'They walk home', translation: 'Ellas caminan a casa' },
          { word: 'together', translation: 'juntas' },
          { word: '.', translation: '' },
          { word: 'Sofia looks at', translation: 'Sofia mira a' },
          { word: 'the dogs in', translation: 'los perros en' },
          { word: 'the street', translation: 'la calle' },
          { word: '.', translation: '' },
          { word: 'She says,', translation: 'Ella dice,' },
          { word: '"Maybe we can', translation: '"Quizás podamos' },
          { word: 'help them too', translation: 'ayudar a ellos también' },
          { word: ',', translation: ',' },
          { word: 'Luna."', translation: 'Luna."' },
          { word: 'Luna barks softly', translation: 'Luna ladra suavemente' },
          { word: ',', translation: ',' },
          { word: 'as if to', translation: 'como si para' },
          { word: 'say,', translation: 'decir,' },
          { word: '"Yes."', translation: '"Sí."' },
        ],
      },
    ],
  },
  {
    id: 7,
    title: 'Together we make a difference',
    titleTranslation: 'Juntos hacemos la diferencia',
    scenes: [
      {
        id: 1,
        image: '/images/7.1.png',
        text: [
          { word: 'Sofia is in', translation: 'Sofia está en' },
          { word: 'her room', translation: 'su habitación' },
          { word: '.', translation: '' },
          { word: 'Luna is sleeping', translation: 'Luna está durmiendo' },
          { word: 'on her bed', translation: 'en su cama' },
          { word: '.', translation: '' },
          { word: 'Sofia looks at', translation: 'Sofia mira a' },
          { word: 'her', translation: 'ella' },
          { word: '.', translation: '' },
          { word: '"You were a', translation: '"Tú eras una' },
          { word: 'street dog', translation: 'perro callejero' },
          { word: '.', translation: '' },
          { word: 'Now you are', translation: 'Ahora tú estás' },
          { word: 'safe," she whispers', translation: 'segura," ella susurra' },
          { word: '.', translation: '' },
          { word: 'She thinks of', translation: 'Ella piensa en' },
          { word: 'other dogs', translation: 'otros perros' },
          { word: '.', translation: '' },
          { word: 'Many still have', translation: 'Muchos todavía no tienen' },
          { word: 'no home', translation: 'hogar' },
          { word: '.', translation: '' },
          { word: '"We have to', translation: '"Debemos ayudar a' },
          { word: 'help them," Sofia says', translation: 'ellos," dice Sofia' },
          { word: '.', translation: '' },
        ],
      },
      {
        id: 2,
        image: '/images/7.2.png',
        text: [
          { word: 'She takes paper', translation: 'Ella toma papel' },
          { word: 'and markers', translation: 'y marcadores' },
          { word: '.', translation: '' },
          { word: 'She writes, "Adopt', translation: 'Ella escribe, "Adopta' },
          { word: ", Don't Shop", translation: ', no compres' },
          { word: '!"', translation: '!"' },
          { word: 'She draws happy', translation: 'Ella dibuja perros' },
          { word: 'dogs and hearts', translation: 'felices y corazones' },
          { word: '.', translation: '' },
          { word: 'She uses blue', translation: 'Ella usa azul' },
          { word: ', red and', translation: ', rojo y' },
          { word: 'yellow', translation: 'amarillo' },
          { word: '.', translation: '' },
          { word: 'She shows the', translation: 'Ella muestra los' },
          { word: 'posters to her', translation: 'carteles a sus' },
          { word: 'parents', translation: 'padres' },
          { word: '.', translation: '' },
          { word: '"These are for', translation: '"Estos son para' },
          { word: 'school," she says', translation: 'la escuela," ella dice' },
          { word: '.', translation: '' },
          { word: 'Her mom smiles', translation: 'Su mamá sonríe' },
          { word: '.', translation: '' },
          { word: '"You have a', translation: '"Tienes un' },
          {
            word: 'big heart," she says',
            translation: 'gran corazón," ella dice',
          },
          { word: '.', translation: '' },
          { word: 'Sofia talks to', translation: 'Sofia habla con' },
          { word: 'her teacher', translation: 'su maestra' },
          { word: '.', translation: '' },
          { word: '"Can we do', translation: '"Podemos hacer un' },
          { word: 'an adoption day?"', translation: 'día de adopción?"' },
          { word: 'The teacher nods', translation: 'La maestra asiente' },
          { word: '.', translation: '' },
          { word: '"Yes! Let\'s invite', translation: '"¡Sí! Invitemos a' },
          {
            word: 'a shelter," she says',
            translation: 'un refugio," ella dice',
          },
          { word: '.', translation: '' },
          { word: 'At home, Sofia', translation: 'En casa, Sofia' },
          { word: 'makes more posters', translation: 'hace más carteles' },
          { word: '.', translation: '' },
          { word: 'Luna watches her', translation: 'Luna la observa' },
          { word: 'color', translation: 'colorear' },
          { word: '.', translation: '' },
        ],
      },
      {
        id: 3,
        image: '/images/7.3.png',
        text: [
          { word: 'At school, Sofia', translation: 'En la escuela, Sofia' },
          { word: 'shares her idea', translation: 'comparte su idea' },
          { word: 'with her friends', translation: 'con sus amigos' },
          { word: '.', translation: '' },
          { word: 'They like it', translation: 'Les gusta' },
          { word: '.', translation: '' },
          { word: 'They help her', translation: 'Ellos la ayudan' },
          { word: 'hang the posters', translation: 'a colgar los carteles' },
          { word: '.', translation: '' },
          { word: 'They put them', translation: 'Los ponen' },
          { word: 'on walls, doors', translation: 'en paredes, puertas' },
          { word: 'and the library', translation: 'y la biblioteca' },
          { word: '.', translation: '' },
          { word: 'Sofia also posts', translation: 'Sofia también publica' },
          { word: 'pictures online', translation: 'fotos en línea' },
          { word: '.', translation: '' },
          { word: 'More people see', translation: 'Más personas ven' },
          { word: 'the message', translation: 'el mensaje' },
          { word: '.', translation: '' },
          { word: 'The teacher says', translation: 'La maestra dice' },
          { word: ',', translation: ',' },
          { word: '"Sofia, you are', translation: '"Sofia, tú eres' },
          { word: 'a leader."', translation: 'una líder."' },
          {
            word: 'Sofia feels proud',
            translation: 'Sofia se siente orgullosa',
          },
          { word: '.', translation: '' },
          { word: 'She hugs Luna', translation: 'Ella abraza a Luna' },
          { word: 'and says, "We', translation: 'y dice, "Estamos' },
          { word: 'are helping now', translation: 'ayudando ahora' },
          { word: ',', translation: ',' },
          { word: 'little hero."', translation: 'pequeña heroína."' },
          { word: 'Luna wags her', translation: 'Luna mueve su' },
          { word: 'tail', translation: 'cola' },
          { word: '.', translation: '' },
          { word: 'Together, they are', translation: 'Juntas, ellas están' },
          { word: 'making a change', translation: 'haciendo un cambio' },
          { word: '.', translation: '' },
        ],
      },
    ],
  },
  {
    id: 8,
    title: 'Reunited',
    titleTranslation: 'Reunidas',
    scenes: [
      {
        id: 1,
        image: '/images/8.1.png',
        text: [
          { word: 'Luna is happy', translation: 'Luna está feliz' },
          { word: '.', translation: '' },
          { word: 'She runs in', translation: 'Ella corre en' },
          { word: 'the garden', translation: 'el jardín' },
          { word: '.', translation: '' },
          { word: 'Her ears bounce', translation: 'Sus orejas rebotan' },
          { word: '.', translation: '' },
          { word: 'Sofia is proud', translation: 'Sofia está orgullosa' },
          { word: '.', translation: '' },
          { word: 'Her posters are', translation: 'Sus carteles están' },
          { word: 'everywhere', translation: 'por todas partes' },
          { word: '.', translation: '' },
          { word: 'They say', translation: 'Ellos dicen' },
          { word: ',', translation: ',' },
          {
            word: '"Adopt, Don’t Shop!"',
            translation: '"¡Adopta, no compres!"',
          },
          { word: '.', translation: '' },
          { word: 'Each one shows', translation: 'Cada uno muestra' },
          { word: 'dogs and cats', translation: 'perros y gatos' },
          { word: 'with big smiles', translation: 'con grandes sonrisas' },
          { word: '.', translation: '' },
          { word: 'They also show', translation: 'También muestran' },
          { word: 'the name of', translation: 'el nombre de' },
          { word: 'a local shelter', translation: 'un refugio local' },
          { word: '.', translation: '' },
          { word: 'One day', translation: 'Un día' },
          { word: ',', translation: ',' },
          { word: 'Sofia and Luna', translation: 'Sofia y Luna' },
          { word: 'visit the shelter', translation: 'visitan el refugio' },
          { word: '.', translation: '' },
          { word: 'Luna sniffs the', translation: 'Luna olfatea el' },
          { word: 'floor', translation: 'suelo' },
          { word: '.', translation: '' },
          { word: 'She walks slowly', translation: 'Ella camina lentamente' },
          { word: 'past the cages', translation: 'frente a las jaulas' },
          { word: '.', translation: '' },
          { word: 'Suddenly', translation: 'De repente' },
          { word: ',', translation: ',' },
          { word: 'she stops', translation: 'ella se detiene' },
          { word: '.', translation: '' },
          { word: 'Her nose moves', translation: 'Su nariz se mueve' },
          { word: 'fast', translation: 'rápido' },
          { word: '.', translation: '' },
          { word: 'She barks', translation: 'Ella ladra' },
          { word: '.', translation: '' },
          { word: 'Inside the cage', translation: 'Dentro de la jaula' },
          { word: 'is a yellow', translation: 'está una amarilla' },
          { word: 'puppy', translation: 'cachorra' },
          { word: '.', translation: '' },
          { word: 'She has a', translation: 'Ella tiene una' },
          { word: 'white moon on', translation: 'luna blanca en' },
          { word: 'her cheek', translation: 'su mejilla' },
          { word: '.', translation: '' },
          { word: 'Sofia gasps', translation: 'Sofia se queda sin aliento' },
          { word: '.', translation: '' },
          { word: '"Luna, it’s your', translation: '"¡Luna, es tu"' },
          { word: 'sister!"', translation: 'hermana!"' },
          { word: 'Luna jumps with', translation: 'Luna salta de' },
          { word: 'joy', translation: 'alegría' },
          { word: '.', translation: '' },
        ],
      },
      {
        id: 2,
        image: '/images/8.2.png',
        text: [
          { word: 'Sofia kneels down', translation: 'Sofia se arrodilla' },
          { word: '.', translation: '' },
          { word: 'She looks at', translation: 'Ella mira a' },
          { word: 'the puppy', translation: 'la cachorra' },
          { word: '.', translation: '' },
          { word: 'The puppy wags', translation: 'La cachorra mueve' },
          { word: 'her tail', translation: 'su cola' },
          { word: '.', translation: '' },
          { word: '"We\'ll take her', translation: '"La llevaremos a ella' },
          { word: 'home," Sofia says', translation: 'a casa," dice Sofia' },
          { word: '.', translation: '' },
          { word: '"You won\'t be', translation: '"No volverán a estar' },
          { word: 'apart again."', translation: 'separadas."' },
          { word: 'She names the', translation: 'Ella nombra a la' },
          { word: 'puppy Sol', translation: 'cachorra Sol' },
          { word: '.', translation: '' },
          { word: 'Her fur shines', translation: 'Su pelaje brilla' },
          { word: 'like the sun', translation: 'como el sol' },
          { word: '.', translation: '' },
          { word: 'Now Sofia, Luna', translation: 'Ahora Sofia, Luna' },
          { word: 'and Sol are', translation: 'y Sol son' },
          { word: 'a team', translation: 'un equipo' },
          { word: '.', translation: '' },
          { word: 'They visit schools', translation: 'Ellas visitan escuelas' },
          { word: '.', translation: '' },
          { word: 'They talk to', translation: 'Ellas hablan con' },
          { word: 'people', translation: 'personas' },
          { word: '.', translation: '' },
          { word: 'They tell their', translation: 'Ellas cuentan su' },
          { word: 'story', translation: 'historia' },
          { word: '.', translation: '' },
          { word: 'More families adopt', translation: 'Más familias adoptan' },
          { word: 'pets', translation: 'mascotas' },
          { word: '.', translation: '' },
          { word: 'More dogs find', translation: 'Más perros encuentran' },
          { word: 'homes', translation: 'hogares' },
          { word: '.', translation: '' },
          { word: "Sofia's heart is", translation: 'El corazón de Sofia está' },
          { word: 'full', translation: 'lleno' },
          { word: '.', translation: '' },
          { word: 'She looks at', translation: 'Ella mira a' },
          { word: 'her two dogs', translation: 'sus dos perros' },
          { word: '.', translation: '' },
          { word: '"You changed my', translation: '"Cambiaste mi' },
          { word: 'life," she says', translation: 'vida," dice ella' },
          { word: '.', translation: '' },
          { word: 'Luna and Sol', translation: 'Luna y Sol' },
          { word: 'wag their tails', translation: 'mueven sus colas' },
          { word: '.', translation: '' },
          { word: 'Together, they walk', translation: 'Juntas, ellas caminan' },
          { word: 'home', translation: 'a casa' },
          { word: '.', translation: '' },
          { word: 'A new adventure', translation: 'Una nueva aventura' },
          { word: 'is just beginning', translation: 'está comenzando' },
          { word: '.', translation: '' },
        ],
      },
    ],
  },
]

export default chapters
