// src/scenes.js

const scenes = [
  {
    id: 1,
    image: '/images/1.1.png',
    text: [
      { word: 'It', translation: 'Es' },
      { word: 'is', translation: 'es' },
      { word: 'a', translation: 'una' },
      { word: 'cold', translation: 'fría' },
      { word: 'night', translation: 'noche' },
      { word: '.', translation: '' },
      { word: 'The', translation: 'El' },
      { word: 'wind', translation: 'viento' },
      { word: 'is', translation: 'es' },
      { word: 'strong', translation: 'fuerte' },
      { word: '.', translation: '' },
      { word: 'The', translation: 'La' },
      { word: 'moon', translation: 'luna' },
      { word: 'is', translation: 'es' },
      { word: 'big', translation: 'grande' },
      { word: 'and', translation: 'y' },
      { word: 'bright', translation: 'brillante' },
      { word: 'in', translation: 'en' },
      { word: 'the', translation: 'el' },
      { word: 'dark', translation: 'oscuro' },
      { word: 'sky', translation: 'cielo' },
      { word: '.', translation: '' },
    ],
  },
  {
    id: 2,
    image: '/images/1.2.png',
    text: [
      { word: 'Mama', translation: 'Mama' },
      { word: 'is', translation: 'es' },
      { word: 'a', translation: 'una' },
      { word: 'stray', translation: 'callejera' },
      { word: 'dog', translation: 'perra' },
      { word: '.', translation: '' },
      { word: 'Her', translation: 'Su' },
      { word: 'fur', translation: 'pelaje' },
      { word: 'is', translation: 'está' },
      { word: 'messy', translation: 'desordenado' },
      { word: '.', translation: '' },
      { word: 'Her', translation: 'Sus' },
      { word: 'eyes', translation: 'ojos' },
      { word: 'are', translation: 'están' },
      { word: 'tired', translation: 'cansados' },
      { word: '.', translation: '' },
      { word: 'Her', translation: 'Su' },
      { word: 'belly', translation: 'vientre' },
      { word: 'is', translation: 'está' },
      { word: 'round', translation: 'redondo' },
      { word: '.', translation: '' },
      { word: 'She', translation: 'Ella' },
      { word: 'is', translation: 'está' },
      { word: 'going', translation: 'va' },
      { word: 'to', translation: 'a' },
      { word: 'have', translation: 'tener' },
      { word: 'puppies', translation: 'cachorros' },
      { word: '.', translation: '' },
      { word: 'She', translation: 'Ella' },
      { word: 'walks', translation: 'camina' },
      { word: 'slowly', translation: 'lentamente' },
      { word: 'into', translation: 'en' },
      { word: 'a', translation: 'un' },
      { word: 'quiet', translation: 'tranquilo' },
      { word: 'alley', translation: 'callejón' },
      { word: '.', translation: '' },
      { word: 'The', translation: 'Las' },
      { word: 'walls', translation: 'paredes' },
      { word: 'are', translation: 'son' },
      { word: 'high', translation: 'altas' },
      { word: '.', translation: '' },
      { word: 'The', translation: 'El' },
      { word: 'space', translation: 'espacio' },
      { word: 'is', translation: 'es' },
      { word: 'small', translation: 'pequeño' },
      { word: '.', translation: '' },
      { word: 'It', translation: 'Se' },
      { word: 'feels', translation: 'siente' },
      { word: 'lonely', translation: 'solitario' },
      { word: '.', translation: '' },
    ],
  },
  {
    id: 3,
    image: '/images/1.3.png',
    text: [
      { word: 'Mama', translation: 'Mama' },
      { word: 'finds', translation: 'encuentra' },
      { word: 'a', translation: 'una' },
      { word: 'corner', translation: 'esquina' },
      { word: '.', translation: '' },
      { word: 'There', translation: 'Hay' },
      { word: 'is', translation: 'es' },
      { word: 'a', translation: 'una' },
      { word: 'cardboard', translation: 'cartón' },
      { word: 'box', translation: 'caja' },
      { word: '.', translation: '' },
      { word: 'It', translation: 'Es' },
      { word: 'is', translation: 'es' },
      { word: 'soft', translation: 'suave' },
      { word: 'and', translation: 'y' },
      { word: 'dry', translation: 'seca' },
      { word: '.', translation: '' },
      { word: 'She', translation: 'Ella' },
      { word: 'lies', translation: 'se acuesta' },
      { word: 'down', translation: 'abajo' },
      { word: 'inside', translation: 'dentro' },
      { word: '.', translation: '' },
      { word: 'She', translation: 'Ella' },
      { word: 'breathes', translation: 'respira' },
      { word: 'deeply', translation: 'profundamente' },
      { word: '.', translation: '' },
      { word: 'She', translation: 'Ella' },
      { word: 'is', translation: 'está' },
      { word: 'ready', translation: 'lista' },
      { word: '.', translation: '' },
    ],
  },
  {
    id: 4,
    image: '/images/1.4.png',
    text: [
      { word: 'One', translation: 'Uno' },
      { word: 'by', translation: 'por' },
      { word: 'one', translation: 'uno' },
      { word: ',', translation: '' },
      { word: 'the', translation: 'los/las' },
      { word: 'puppies', translation: 'cachorros' },
      { word: 'are', translation: 'son/están' },
      { word: 'born', translation: 'nacidos' },
      { word: '.', translation: '' },
      { word: 'The', translation: 'El/La' },
      { word: 'first', translation: 'primero' },
      { word: 'is', translation: 'es/está' },
      { word: 'black', translation: 'negro' },
      { word: '.', translation: '' },
      { word: 'The', translation: 'El/La' },
      { word: 'second', translation: 'segundo' },
      { word: 'is', translation: 'es/está' },
      { word: 'also', translation: 'también' },
      { word: 'black', translation: 'negro' },
      { word: '.', translation: '' },
      { word: 'The', translation: 'El/La' },
      { word: 'third', translation: 'tercero' },
      { word: 'is', translation: 'es/está' },
      { word: 'light', translation: 'claro' },
      { word: 'orange', translation: 'naranja' },
      { word: '.', translation: '' },
      { word: 'Mama', translation: 'Mamá' },
      { word: 'looks', translation: 'mira' },
      { word: 'at', translation: 'a' },
      { word: 'them', translation: 'ellos' },
      { word: 'with', translation: 'con' },
      { word: 'love', translation: 'amor' },
      { word: '.', translation: '' },
      { word: 'She', translation: 'Ella' },
      { word: 'licks', translation: 'lame' },
      { word: 'them', translation: 'ellos' },
      { word: 'gently', translation: 'suavemente' },
      { word: '.', translation: '' },
    ],
  },
  {
    id: 5,
    image: '/images/1.5.png',
    text: [
      { word: 'She', translation: 'Ella' },
      { word: 'tries', translation: 'intenta' },
      { word: 'to', translation: 'a' },
      { word: 'feed', translation: 'alimentar' },
      { word: 'them', translation: 'ellos' },
      { word: ',', translation: '' },
      { word: 'but', translation: 'pero' },
      { word: 'there', translation: 'hay' },
      { word: 'is', translation: 'es/está' },
      { word: 'not', translation: 'no' },
      { word: 'enough', translation: 'suficiente' },
      { word: 'milk', translation: 'leche' },
      { word: '.', translation: '' },
      { word: 'Her', translation: 'Su' },
      { word: 'tummy', translation: 'panza' },
      { word: 'growls', translation: 'ruge' },
      { word: '.', translation: '' },
      { word: 'She', translation: 'Ella' },
      { word: 'is', translation: 'es/está' },
      { word: 'hungry', translation: 'hambrienta' },
      { word: '.', translation: '' },
      { word: 'Her', translation: 'Sus' },
      { word: 'legs', translation: 'piernas' },
      { word: 'are', translation: 'son/están' },
      { word: 'weak', translation: 'débiles' },
      { word: '.', translation: '' },
      { word: 'She', translation: 'Ella' },
      { word: 'wants', translation: 'quiere' },
      { word: 'to', translation: 'a' },
      { word: 'find', translation: 'encontrar' },
      { word: 'food', translation: 'comida' },
      { word: '.', translation: '' },
      { word: 'She', translation: 'Ella' },
      { word: 'walks', translation: 'camina' },
      { word: 'out', translation: 'fuera' },
      { word: 'of', translation: 'de' },
      { word: 'the', translation: 'el/la' },
      { word: 'alley', translation: 'callejón' },
      { word: '.', translation: '' },
      { word: 'She', translation: 'Ella' },
      { word: 'checks', translation: 'revisa' },
      { word: 'trash', translation: 'basura' },
      { word: 'cans', translation: 'botes' },
      { word: '.', translation: '' },
      { word: 'She', translation: 'Ella' },
      { word: 'finds', translation: 'encuentra' },
      { word: 'a', translation: 'un/una' },
      { word: 'small', translation: 'pequeño' },
      { word: 'piece', translation: 'pedazo' },
      { word: 'of', translation: 'de' },
      { word: 'sandwich', translation: 'sándwich' },
      { word: 'and', translation: 'y' },
      { word: 'eats', translation: 'come' },
      { word: 'it', translation: 'eso' },
      { word: 'fast', translation: 'rápido' },
      { word: '.', translation: '' },
      { word: 'She', translation: 'Ella' },
      { word: 'drinks', translation: 'bebe' },
      { word: 'from', translation: 'de' },
      { word: 'a', translation: 'un/una' },
      { word: 'puddle', translation: 'charco' },
      { word: '.', translation: '' },
      { word: 'The', translation: 'El/La' },
      { word: 'water', translation: 'agua' },
      { word: 'is', translation: 'es/está' },
      { word: 'grey', translation: 'gris' },
      { word: 'and', translation: 'y' },
      { word: 'sour', translation: 'agria' },
      { word: ',', translation: '' },
      { word: 'but', translation: 'pero' },
      { word: 'she', translation: 'ella' },
      { word: 'is', translation: 'está' },
      { word: 'thirsty', translation: 'sedienta' },
      { word: '.', translation: '' },
    ],
  },
]

export default scenes
