const scenes = [
  {
    id: 1,
    text: [
      { word: 'In', translation: 'En' },
      { word: 'the', translation: 'el/la' },
      { word: 'village', translation: 'aldea/pueblo' },
      { word: 'of', translation: 'de' },
      { word: 'Seattle', translation: '(nombre propio)' },
      { word: ',', translation: '' },
      { word: 'a', translation: 'un/una' },
      { word: 'young', translation: 'joven' },
      { word: 'boy', translation: 'niño' },
      { word: 'named', translation: 'llamado' },
      { word: 'Doni', translation: '(nombre otomí)' },
      { word: 'lived', translation: 'vivía' },
      { word: 'with', translation: 'con' },
      { word: 'his', translation: 'su' },
      { word: 'family', translation: 'familia' },
      { word: '.', translation: '' },
      { word: 'Oh', translation: 'Oh' },
      { word: ',', translation: '' },
      { word: 'what', translation: 'qué' },
      { word: 'a', translation: 'un' },
      { word: 'beautiful', translation: 'hermoso' },
      { word: 'day', translation: 'día' },
      { word: '!', translation: '' },
      { word: "Let's", translation: 'Vamos a' },
      { word: 'explore', translation: 'explorar' },
      { word: 'the', translation: 'el/la' },
      { word: 'forest', translation: 'bosque' },
      { word: '...', translation: '' },
      { word: 'together', translation: 'juntos' },
      { word: '.', translation: '' },
    ],
  },
]

export default scenes
